default_context:
  project_name: 'fastapi-vue-postgresql'
  project_slug: 'fastapi-vue-postgresql'
  domain_main: 'fastapi-vue-postgresql.sasha.ga'
  domain_staging: 'stag.fastapi-vue-postgresql.sasha.ga'
  docker_swarm_stack_name_main: 'fastapi-vue-postgresql-sasha-ga'
  docker_swarm_stack_name_staging: 'stag-fastapi-vue-postgresql-sasha-ga'
  secret_key: '81761919ed32e50b62ab73ecff7954fa25be13e20641d9ef7ea2768433634fc8'
  first_superuser: 'admin@fastapi-vue-postgresql.sasha.ga'
  first_superuser_password: '2Doe%hew'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.fastapi-vue-postgresql.sasha.ga", "https://stag.fastapi-vue-postgresql.sasha.ga", "https://fastapi-vue-postgresql.sasha.ga", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: 'smtp.mail.yahoo.com'
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@fastapi-vue-postgresql.sasha.ga'
  postgres_password: '%4rHE&Uo'
  pgadmin_default_user: 'admin@fastapi-vue-postgresql.sasha.ga'
  pgadmin_default_user_password: '2Doe%hew'
  traefik_constraint_tag: 'fastapi-vue-postgresql.sasha.ga'
  traefik_constraint_tag_staging: 'stag.fastapi-vue-postgresql.sasha.ga'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:2Doe%hew'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
